### ISSUE TITLE
misspelled reason argument in index.js

### ISSUE THREAD

**Issue by resetium** [WittySmirk/A-Regular-Bot#1]
check !ban fam
you spelled it as "resson"

**Comment by WittySmirk** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/d27a2dfb-c3b9-44fd-8e5e-4e3068049585-1aae06eb-56ed-4ac3-be5f-369f84b86b03-v1.png?transparent=1&palette=1&width=246)
